apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: '129'
    field.cattle.io/publicEndpoints: 'null'
    kubectl.kubernetes.io/last-applied-configuration: >-
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"name":"auto-test"},"name":"auto-test","namespace":"biz"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"auto-test"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"labels":{"app":"auto-test","log-type":"java","qcloud-app":"auto-test"}},"spec":{"containers":[{"args":["sh","/data/www/init.sh"],"env":[{"name":"aliyun.logs.auto-test","value":"/data/logs/grantTEST_VERSION/*.log"},{"name":"aliyun.logs.auto-test.format","value":"json"}],"image":"registry.kuainiujinke.com/cd_biz/auto-vue:v3.1.1","imagePullPolicy":"Always","name":"auto-test","resources":{"limits":{"cpu":"2000m","memory":"1500Mi"},"requests":{"cpu":"100m","memory":"128Mi"}},"volumeMounts":[{"mountPath":"/data/logs","name":"logs"}]}],"hostAliases":[{"hostnames":["oa.kuainiu.io"],"ip":"101.34.175.3"}],"imagePullSecrets":[{"name":"kuainiujinke-registry"}],"nodeSelector":{"kubernetes.io/hostname":"10.1.5.10"},"terminationGracePeriodSeconds":45,"volumes":[{"hostPath":{"path":"/data/logs","type":"Directory"},"name":"logs"}]}}}}
  creationTimestamp: '2022-12-26T02:41:36Z'
  generation: 168
  labels:
    name: auto-test
  managedFields:
    - apiVersion: apps/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations: {}
          f:labels:
            .: {}
            f:name: {}
        f:spec:
          f:progressDeadlineSeconds: {}
          f:revisionHistoryLimit: {}
          f:selector:
            f:matchLabels:
              .: {}
              f:app: {}
          f:strategy:
            f:rollingUpdate:
              .: {}
              f:maxSurge: {}
            f:type: {}
          f:template:
            f:metadata:
              f:labels:
                .: {}
                f:app: {}
                f:log-type: {}
                f:qcloud-app: {}
            f:spec:
              f:containers:
                k:{"name":"auto-test"}:
                  .: {}
                  f:args: {}
                  f:env:
                    .: {}
                    k:{"name":"aliyun.logs.auto-test"}:
                      .: {}
                      f:name: {}
                      f:value: {}
                    k:{"name":"aliyun.logs.auto-test.format"}:
                      .: {}
                      f:name: {}
                      f:value: {}
                  f:name: {}
                  f:resources:
                    .: {}
                    f:limits:
                      .: {}
                      f:memory: {}
                    f:requests: {}
                  f:terminationMessagePath: {}
                  f:terminationMessagePolicy: {}
                  f:volumeMounts:
                    .: {}
                    k:{"mountPath":"/data/logs"}:
                      .: {}
                      f:mountPath: {}
                      f:name: {}
              f:dnsPolicy: {}
              f:hostAliases:
                .: {}
                k:{"ip":"101.34.175.3"}:
                  .: {}
                  f:hostnames: {}
                  f:ip: {}
              f:imagePullSecrets:
                .: {}
                k:{"name":"kuainiujinke-registry"}:
                  .: {}
                  f:name: {}
              f:restartPolicy: {}
              f:schedulerName: {}
              f:securityContext: {}
              f:terminationGracePeriodSeconds: {}
              f:volumes:
                .: {}
                k:{"name":"logs"}:
                  .: {}
                  f:hostPath:
                    .: {}
                    f:path: {}
                    f:type: {}
                  f:name: {}
      manager: kubectl-client-side-apply
      operation: Update
      time: '2022-12-26T02:41:36Z'
    - apiVersion: apps/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            f:kubectl.kubernetes.io/last-applied-configuration: {}
        f:spec:
          f:strategy:
            f:rollingUpdate:
              f:maxUnavailable: {}
          f:template:
            f:metadata:
              f:annotations: {}
            f:spec:
              f:affinity:
                .: {}
                f:nodeAffinity:
                  .: {}
                  f:requiredDuringSchedulingIgnoredDuringExecution: {}
              f:dnsConfig: {}
      manager: rancher
      operation: Update
      time: '2023-08-07T11:16:15Z'
    - apiVersion: apps/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            f:field.cattle.io/publicEndpoints: {}
        f:spec:
          f:replicas: {}
          f:template:
            f:metadata:
              f:annotations:
                f:cattle.io/timestamp: {}
            f:spec:
              f:affinity:
                f:nodeAffinity:
                  f:requiredDuringSchedulingIgnoredDuringExecution:
                    f:nodeSelectorTerms: {}
              f:containers:
                k:{"name":"auto-test"}:
                  f:image: {}
                  f:imagePullPolicy: {}
                  f:resources:
                    f:limits:
                      f:cpu: {}
                    f:requests:
                      f:cpu: {}
                      f:memory: {}
      manager: agent
      operation: Update
      time: '2023-08-08T08:23:13Z'
    - apiVersion: apps/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            f:deployment.kubernetes.io/revision: {}
        f:status:
          f:availableReplicas: {}
          f:conditions:
            .: {}
            k:{"type":"Available"}:
              .: {}
              f:lastTransitionTime: {}
              f:lastUpdateTime: {}
              f:message: {}
              f:reason: {}
              f:status: {}
              f:type: {}
            k:{"type":"Progressing"}:
              .: {}
              f:lastTransitionTime: {}
              f:lastUpdateTime: {}
              f:message: {}
              f:reason: {}
              f:status: {}
              f:type: {}
          f:observedGeneration: {}
          f:readyReplicas: {}
          f:replicas: {}
          f:updatedReplicas: {}
      manager: kube-controller-manager
      operation: Update
      time: '2023-08-08T10:26:43Z'
  name: auto-test
  namespace: biz
  resourceVersion: '50048370588'
  selfLink: /apis/apps/v1/namespaces/biz/deployments/auto-test
  uid: e245dd4e-053d-4b09-bbb1-13affb1e5c78
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: auto-test
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        cattle.io/timestamp: '2023-08-08T08:23:13Z'
      creationTimestamp: null
      labels:
        app: auto-test
        log-type: java
        qcloud-app: auto-test
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - 10.1.7.13
      containers:
        - args:
            - sh
            - /data/www/init.sh
          env:
            - name: aliyun.logs.auto-test
              value: /data/logs/grantTEST_VERSION/*.log
            - name: aliyun.logs.auto-test.format
              value: json
          image: registry.kuainiujinke.com/cd_biz/auto-vue:v3.2.1
          imagePullPolicy: Always
          name: auto-test
          resources:
            limits:
              cpu: 500m
              memory: 1500Mi
            requests:
              cpu: '0'
              memory: '0'
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /data/logs
              name: logs
      dnsConfig: {}
      dnsPolicy: ClusterFirst
      hostAliases:
        - hostnames:
            - oa.kuainiu.io
          ip: 101.34.175.3
      imagePullSecrets:
        - name: kuainiujinke-registry
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 45
      volumes:
        - hostPath:
            path: /data/logs
            type: Directory
          name: logs
status:
  availableReplicas: 1
  conditions:
    - lastTransitionTime: '2023-06-01T06:29:42Z'
      lastUpdateTime: '2023-08-08T08:23:17Z'
      message: ReplicaSet "auto-test-b6d9f864f" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: 'True'
      type: Progressing
    - lastTransitionTime: '2023-08-08T10:26:43Z'
      lastUpdateTime: '2023-08-08T10:26:43Z'
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: 'True'
      type: Available
  observedGeneration: 168
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
