# coding: utf-8
from sqlalchemy.dialects.mysql import ENUM

from app import db


class AssetRbiz(db.Model):
    __tablename__ = 'asset'
    __table_args__ = {"useexisting": True}
    asset_id = db.Column(db.Integer, primary_key=True, info='资产行号，单表主键')
    asset_no = db.Column(db.String(20), nullable=False, server_default=db.FetchedValue(), info='资产主键')
    asset_item_no = db.Column(db.String(48), nullable=False, unique=True, server_default=db.FetchedValue(), info='项目编号，有一系列规则，用来标识某个项目，可以从项目编号里看到很多信息')
    asset_type = db.Column(db.String(32), nullable=False, server_default=db.FetchedValue(), info='资产类型')
    asset_sub_type = db.Column(db.String(32), nullable=False, server_default=db.FetchedValue())
    asset_period_type = db.Column(ENUM('month', 'day'), nullable=False, server_default=db.FetchedValue(), info='还款周期类型')
    asset_period_count = db.Column(db.SmallInteger, nullable=False, server_default=db.FetchedValue(), info='还款总期数')
    asset_product_category = db.Column(db.String(16), nullable=False, server_default=db.FetchedValue(), info='资产类别名称：14天，30天，3个月，6个月')
    asset_cmdb_product_number = db.Column(db.String(48), nullable=False, server_default=db.FetchedValue(), info='资产产品在费率系统编号')
    asset_grant_at = db.Column(db.DateTime, nullable=False, server_default=db.FetchedValue(), info='放款时间')
    asset_effect_at = db.Column(db.DateTime, nullable=False, server_default=db.FetchedValue(), info='合同生效日')
    asset_actual_grant_at = db.Column(db.DateTime, nullable=False, server_default=db.FetchedValue(), info='实际放款日')
    asset_due_at = db.Column(db.DateTime, nullable=False, server_default=db.FetchedValue(), info='资产到期日')
    asset_payoff_at = db.Column(db.DateTime, nullable=False, index=True, server_default=db.FetchedValue(), info='偿清时间')
    asset_from_system = db.Column(db.String(24), nullable=False, server_default=db.FetchedValue())
    asset_status = db.Column(ENUM('sign', 'sale', 'repay', 'payoff', 'void', 'writeoff', 'late', 'lateoff'), nullable=False, server_default=db.FetchedValue(), info='资产状态')
    asset_principal_amount = db.Column(db.BigInteger, nullable=False, server_default=db.FetchedValue(), info='合同本金(不包含减免)')
    asset_granted_principal_amount = db.Column(db.BigInteger, nullable=False, server_default=db.FetchedValue(), info='实际放款本金')
    asset_decrease_principal_amount = db.Column(db.BigInteger, nullable=False, server_default=db.FetchedValue(), info='本金减免')
    asset_loan_channel = db.Column(db.String(32), nullable=False, server_default=db.FetchedValue(), info='放款渠道')
    asset_alias_name = db.Column(db.String(64), nullable=False, server_default=db.FetchedValue(), info='资产名称')
    asset_interest_amount = db.Column(db.BigInteger, nullable=False, server_default=db.FetchedValue(), info='利息总金额(不包括减免)')
    asset_decrease_interest_amount = db.Column(db.BigInteger, nullable=False, server_default=db.FetchedValue(), info='利息减免金额')
    asset_fee_amount = db.Column(db.BigInteger, nullable=False, server_default=db.FetchedValue(), info='费总金额(不包括减免)')
    asset_decrease_fee_amount = db.Column(db.BigInteger, nullable=False, server_default=db.FetchedValue(), info='费用减免金额')
    asset_balance_amount = db.Column(db.BigInteger, nullable=False, server_default=db.FetchedValue(), info='剩余未偿还总金额(分）包括：本，息，费(=principal_amt+interest_amount+fee_amount-repaid)')
    asset_repaid_amount = db.Column(db.BigInteger, nullable=False, server_default=db.FetchedValue(), info='已偿还总金额(已还本息费)')
    asset_total_amount = db.Column(db.BigInteger, nullable=False, server_default=db.FetchedValue(), info='本息费总额(=principal_amount+decrease+interest_amount+decrease+fee_amount+decrease)。')
    asset_interest_rate = db.Column(db.Numeric(10, 3), nullable=False, server_default=db.FetchedValue(), info='利率')
    asset_create_at = db.Column(db.DateTime, nullable=False, index=True, server_default=db.FetchedValue(), info='创建时间')
    asset_rbiz_create_at = db.Column(db.DateTime, nullable=False, server_default=db.FetchedValue(), info='rbiz创建时间')
    asset_update_at = db.Column(db.DateTime, nullable=False, index=True, server_default=db.FetchedValue())
    asset_rbiz_update_at = db.Column(db.DateTime, nullable=False, server_default=db.FetchedValue(), info='rbiz更新时间')
    asset_last_sync_time = db.Column(db.DateTime, nullable=False, server_default=db.FetchedValue(), info='资产上次同步时间')
    asset_channel_id = db.Column(db.Integer, server_default=db.FetchedValue(), info='渠道id')
    asset_from_system_name = db.Column(db.String(24), nullable=False, server_default=db.FetchedValue(), info='资产来源系统名称')
    asset_owner = db.Column(db.String(24), nullable=False, server_default=db.FetchedValue(), info='资产所有权者')
    asset_actual_payoff_at = db.Column(db.DateTime, index=True, server_default=db.FetchedValue(), info='实际结清时间')
    asset_late_amount = db.Column(db.BigInteger, server_default=db.FetchedValue(), info='包含所有的逾期费用')
    asset_due_bill_no = db.Column(db.String(50), index=True, server_default=db.FetchedValue(), info='资方合同编号')
    asset_repaid_principal_amount = db.Column(db.BigInteger, server_default=db.FetchedValue(), info='已还本金金额')
    asset_repaid_interest_amount = db.Column(db.BigInteger, server_default=db.FetchedValue(), info='已还利息金额')
    asset_repaid_fee_amount = db.Column(db.BigInteger, server_default=db.FetchedValue(), info='已还费用金额')
    asset_repaid_late_amount = db.Column(db.BigInteger, server_default=db.FetchedValue(), info='已还逾期费用金额')
    asset_decrease_late_amount = db.Column(db.BigInteger, server_default=db.FetchedValue(), info='减免费用金额')
    asset_from_app = db.Column(db.String(30), nullable=False, server_default=db.FetchedValue(), info='马甲包')
    asset_repayment_app = db.Column(db.String(10), nullable=False, server_default=db.FetchedValue())
